services:
  bianblog:
    build:
      context: ./vanblog
      dockerfile: Dockerfile
      args:
        BIAN_BLOG_BUILD_SERVER: http://127.0.0.1:3000
        BIAN_BLOG_VERSIONS: bianblog-local
    image: bianblog:local
    container_name: bianblog_app
    restart: always
    depends_on:
      - mongo
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      # 用于自动申请 https 证书，建议改成你的邮箱
      EMAIL: ${BIANBLOG_EMAIL:-admin@example.com}
    volumes:
      - ./vanblog-runtime/data/static:/app/static
      - ./vanblog-runtime/log:/var/log
      - ./vanblog-runtime/caddy/config:/root/.config/caddy
      - ./vanblog-runtime/caddy/data:/root/.local/share/caddy
    ports:
      - "${BIANBLOG_HTTP_PORT:-8080}:80"
      - "${BIANBLOG_HTTPS_PORT:-8443}:443"

  mongo:
    image: mongo:4.4.16
    container_name: bianblog_mongo
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ./vanblog-runtime/data/mongo:/data/db
